version: '3'

services:
  ocr_service:
    build: ocr_service/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: ocr_service

  streamlit:
    build: streamlit/
    depends_on:
      - ocr_service
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge